[package]
name = "rfetch"
version = "0.1.0"
edition = "2024"

[dependencies]
raw-cpuid = "11.5.0"

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "off"
codegen-units = 1
panic = "abort"
